name: Publish to npm

on:
  push:
    branches:
      - refs/tags/*

jobs:
  build:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'bump')"
    steps:
    - uses: actions/checkout@v1
    - name: Set up NodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Global deps
      run: |
        yarn global add lerna
    - name: Clean
      run: |
        yarn run clean
    - name: Install dependencies
      run: |
        HUSKY_SKIP_INSTALL=1 yarn bootstrap
    - name: Configure repo
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin master --tags
    - run: yarn build
    - name: Publish to NPM
      run: yarn publish
      env:
        YARN_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    # - uses: actions/setup-node@v1
    #   with:
    #     registry-url: 'https://npm.pkg.github.com'
